arm_joint_effort_controller:
  type: effort_controllers/JointGroupEffortController
  joints:
    - joint1
    - joint2
  gains:
    joint1: {p: 100.0, i: 0.01, d: 10.0}
    joint2: {p: 100.0, i: 0.01, d: 10.0}
